### ISSUE TITLE
TODO Microservices

### ISSUE THREAD

**Issue by Fazzani** [Fazzani/Synker2#142]
- [ ] Mail notification consumer in batch microservice
- [ ] Push notification consumer in webApi
- [ ] Save message to Database
- [ ] Trace notification ( Error & informations)
